services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: odontologia_oracle
    environment:
      - ORACLE_PASSWORD=Admin123Password!
      - APP_USER=odontologia_user
      - APP_PASSWORD=Odontologia123!
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - odontologia_network

  # backend-api:
  #   build:
  #     context: ./Backend_Odontologia
  #     dockerfile: Dockerfile
  #   container_name: backend-api
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - ASPNETCORE_HTTP_PORTS=5000
  #   depends_on:
  #     - oracle-db
  #   networks:
  #     - odontologia_network

  # evolution-whatsapp:
  #   image: atendai/evolution-api:v2.1.1
  #   container_name: evolution_whatsapp
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - AUTHENTICATION_API_KEY=CLAVE_SECRETA_ODONTO_2026
  #     - WEBHOOK_GLOBAL_ENABLED=true
  #     - WEBHOOK_GLOBAL_URL=http://agente-python:8000/webhook/whatsapp
  #     - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
  #   volumes:
  #     - evolution_instances:/evolution/instances
  #   networks:
  #     - odontologia_network

  qdrant-db:
    image: qdrant/qdrant:v1.11.0
    container_name: qdrant_vector
    ports:
      - "6333:6333"
    networks:
      - odontologia_network

  agente-python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agente_python
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - QDRANT_URL=http://qdrant-db:6333
      - EVOLUTION_API_URL=http://evolution-whatsapp:8080
      - DOTNET_API_URL=http://backend-api:5000/api/v1
    depends_on:
      - qdrant-db
    networks:
      - odontologia_network

volumes:
  oracle_data:
  evolution_instances:

networks:
  odontologia_network:
    driver: bridge